### ISSUE TITLE
Several vulns reported via github

### ISSUE THREAD

**Issue by toddr** [yusukebe/App-revealup#12]
I wanted to pass these reports on from github in the event you're not getting your own reports via https://github.com/yusukebe/App-revealup/network/alert

![Screen Shot 2020-04-03 at 8 54 41 AM](https://user-images.githubusercontent.com/97892/78368134-c3d8f880-7588-11ea-88b1-27b58a9b3ab2.png)

This was detected via https://github.com/metacpan/metacpan-cpan-extracted/

**Comment by robrwo** [comment]
Also https://security.snyk.io/vuln/SNYK-JS-REVEALJS-2414032

**Comment by yusukebe** [comment]
Fixed it in this commit c8fea67994b1aa6d734066bff9ada4e834b09cb7
