### ISSUE TITLE
printing slide as pdf doest not work properly

### ISSUE THREAD

**Issue by akawhy** [yusukebe/App-revealup#8]
When print the slide as pdf in chrome, the result is not good. 

I find this has something to do with `revealjs`. When update `revealjs` to **3.0.0**, the problem is solved.

**Comment by yusukebe** [comment]
@akawhy Thank your request!

`revealjs` in this `App::revealup` has been updated and upload to the CPAN repository. So, you can use new version by typing `cpanm App::revealup` .

If printable pdf layout is not good yet, please give me pull-request or issue!
